sources:
  include:
    - Sources
templates:
  include:
    - Sources/Common/CodeGeneration/Templates
  exclude:
    - Sources/Common/CodeGeneration/Templates/AutoCases.stencil
    - Sources/Common/CodeGeneration/Templates/AutoEquatable.stencil
    - Sources/Common/CodeGeneration/Templates/AutoHashable.stencil
    - Sources/Common/CodeGeneration/Templates/AutoLenses.stencil

output: Sources/Common/CodeGeneration
