line_length:
  warning: 145
  error: 145
  ignores_comments: true
file_length:
  warning: 500
  error: 1000
type_body_length:
  warning: 300
  error: 350
function_parameter_count:
  warning: 6
  error: 8
nesting:
  type_level: 6
identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - fn
    - v1
    - v2
type_name:
  min_length:
    warning: 2
    error: 1
  excluded:
    - Id
    - V1
    - V2
cyclomatic_complexity:
  warning: 12
  error: 14
disabled_rules:
  - force_try
  - force_cast
excluded:
  - Carthage
  - Crashlytics.framework
  - Sources/Common/CodeGeneration
  - Pods
  - .build
  - DerivedData
opt_in_rules: # some rules are only opt-in
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - implicit_return
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - sorted_imports
  - syntactic_sugar
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
custom_rules:
  double_space: # from https://github.com/IBM-Swift/Package-Builder
    include: "*.swift"
    name: "Double space"
    regex: '([a-z,A-Z] \s+)'
    message: "Double space between keywords"
    match_kinds: keyword
    severity: warning
  comments_space: # from https://github.com/brandenr/swiftlintconfig
    name: "Space After Comment"
    regex: '(^ *//\w+)'
    message: "There should be a space after //"
    severity: warning
  unnecessary_type: # from https://github.com/brandenr/swiftlintconfig
    name: "Unnecessary Type"
    regex: '[ a-zA-Z0-9]*(?:let|var) [ a-zA-Z0-9]*: ([a-zA-Z0-9]*)[ ]*= \1'
    message: "Type Definition Not Needed"
    severity: error