osx_image: xcode10.1
language: objective-c
xcode_project: SwiftRex.xcodeproj
xcode_scheme: SwiftRex macOS RxSwift
cache:
  directories:
    - bundler
    - cocoapods
    - vendor/bundle
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="SwiftRex"
before_install:
  - brew update
  - brew install swiftlint || brew outdated swiftlint || brew upgrade swiftlint
  - brew install sourcery || brew outdated sourcery || brew upgrade sourcery
install:
  - bundle install --path vendor/bundle
script:
  - make test-all
after_success:
  - bundle exec slather
